package swift

import (
	"fmt"
	"os"
	"strings"
	"time"
)

const spcOutlookSwiftTopComment = `// This file was generated by generative/generators/swift/spc_outlooks_enum.go.
// Please do not hand write.

import Foundation

`

const spcOutlookEnumConversion = `func SPCOutlookTypesOptions() -> Array<Option> {
    var convertAlerts: Array<Option> = []
    let allAlertsEnums: Array<SPCOutlookTypes> = SPCOutlookTypes.allCases
    
    for alert in allAlertsEnums {
        convertAlerts.append(Option(name: alert.rawValue))
    }
    
    return convertAlerts
}
`

func GenerateSpcOutlookSwift() {
	// Read the contents of the file
	filePath := "generators/templates/spc_outlooks.txt"
	content, err := os.ReadFile(filePath)
	if err != nil {
		fmt.Printf("Failed to read file: %v\n", err)
		return
	}

	// Split the content into lines
	lines := strings.Split(string(content), "\n")

	// Add generated time
	generated := "// Generated on " + time.Now().String() + "\n"

	// Add block comment
	generated += spcOutlookSwiftTopComment

	generated += "enum SPCOutlookTypes: String, CaseIterable {\n"

	// Process each line of the file
	for _, line := range lines {
		line = strings.TrimSpace(line)

		// Skip empty lines
		if line == "" {
			continue
		}

		// Extract the day and category
		spacelessString := strings.ReplaceAll(line, " ", "")

		// Generate the Swift enum case
		enumCase := fmt.Sprintf("\tcase %s = \"%s\"\n", spacelessString, line)
		generated += enumCase
	}

	// Close the Swift enum
	generated += "}\n\n"

	// Write enum conversion generated
	generated += spcOutlookEnumConversion

	// Write the generated Swift enum generated to a file
	file, err := os.Create("swift/SPCOutlooks.swift")
	if err != nil {
		fmt.Printf("Error creating file: %v\n", err)
		return
	}
	defer file.Close()

	file.Write([]byte(generated))
}
