// Generated on 2024-01-13 14:28:50.533655 -0600 CST m=+0.001154376
// This file was generated by generative/generators/golang/convective_outlook_types.gp
// Please do not hand write.

package golang

type ConvectiveOutlookType string

const (
	Day1Categorical              ConvectiveOutlookType = "Day 1 Categorical"
	Day1Tornado                  ConvectiveOutlookType = "Day 1 Tornado"
	Day1Wind                     ConvectiveOutlookType = "Day 1 Wind"
	Day1Hail                     ConvectiveOutlookType = "Day 1 Hail"
	Day1SignificantTornado       ConvectiveOutlookType = "Day 1 Significant Tornado"
	Day1SignificantWind          ConvectiveOutlookType = "Day 1 Significant Wind"
	Day1SignificantHail          ConvectiveOutlookType = "Day 1 Significant Hail"
	Day2Categorical              ConvectiveOutlookType = "Day 2 Categorical"
	Day2Tornado                  ConvectiveOutlookType = "Day 2 Tornado"
	Day2Wind                     ConvectiveOutlookType = "Day 2 Wind"
	Day2Hail                     ConvectiveOutlookType = "Day 2 Hail"
	Day2SignificantTornado       ConvectiveOutlookType = "Day 2 Significant Tornado"
	Day2SignificantWind          ConvectiveOutlookType = "Day 2 Significant Wind"
	Day2SignificantHail          ConvectiveOutlookType = "Day 2 Significant Hail"
	Day3Categorical              ConvectiveOutlookType = "Day 3 Categorical"
	Day3Probabilistic            ConvectiveOutlookType = "Day 3 Probabilistic"
	Day3SignificantProbabilistic ConvectiveOutlookType = "Day 3 Significant Probabilistic"
	Day4Probabilistic            ConvectiveOutlookType = "Day 4 Probabilistic"
	Day5Probabilistic            ConvectiveOutlookType = "Day 5 Probabilistic"
	Day6Probabilistic            ConvectiveOutlookType = "Day 6 Probabilistic"
	Day7Probabilistic            ConvectiveOutlookType = "Day 7 Probabilistic"
	Day8Probabilistic            ConvectiveOutlookType = "Day 8 Probabilistic"
)
