// Generated on 2023-06-24 20:34:38.101208 -0500 CDT m=+0.001647001
// This file was generated by generative/generators/golang/spc_outlooks_enum_go.golang.
// Please do not hand write.

package golang

type SPCOutlookType string

const (
	Day1Categorical              SPCOutlookType = "Day 1 Categorical"
	Day1Tornado                  SPCOutlookType = "Day 1 Tornado"
	Day1Wind                     SPCOutlookType = "Day 1 Wind"
	Day1Hail                     SPCOutlookType = "Day 1 Hail"
	Day1SignificantTornado       SPCOutlookType = "Day 1 Significant Tornado"
	Day1SignificantWind          SPCOutlookType = "Day 1 Significant Wind"
	Day1SignificantHail          SPCOutlookType = "Day 1 Significant Hail"
	Day2Categorical              SPCOutlookType = "Day 2 Categorical"
	Day2Tornado                  SPCOutlookType = "Day 2 Tornado"
	Day2Wind                     SPCOutlookType = "Day 2 Wind"
	Day2Hail                     SPCOutlookType = "Day 2 Hail"
	Day2SignificantTornado       SPCOutlookType = "Day 2 Significant Tornado"
	Day2SignificantWind          SPCOutlookType = "Day 2 Significant Wind"
	Day2SignificantHail          SPCOutlookType = "Day 2 Significant Hail"
	Day3Categorical              SPCOutlookType = "Day 3 Categorical"
	Day3Probabilistic            SPCOutlookType = "Day 3 Probabilistic"
	Day3SignificantProbabilistic SPCOutlookType = "Day 3 Significant Probabilistic"
	Day4Probabilistic            SPCOutlookType = "Day 4 Probabilistic"
	Day5Probabilistic            SPCOutlookType = "Day 5 Probabilistic"
	Day6Probabilistic            SPCOutlookType = "Day 6 Probabilistic"
	Day7Probabilistic            SPCOutlookType = "Day 7 Probabilistic"
	Day8Probabilistic            SPCOutlookType = "Day 8 Probabilistic"
)
