name: CI

on: 
  push
      
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Kickoff release
        id: release
        if: github.ref == 'refs/heads/master'
        uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: patch
          tag_prefix: v

      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup golang
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22.0'

      - name: Build weather-common
        run: go build ./...

  build-weather-db-migration:
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4.1.6

      - name: Login to Tailscale
        uses: tailscale/github-action@main
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Login to docker
        uses: docker/login-action@v3.3.0
        with:
          registry: git.prod.carsonnetworks.net
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_PAT }}

      - name: Build docker image
        run: docker build . -t git.prod.carsonnetworks.net/cdmeyer/weather-db-migrations:${{github.run_number}}
        working-directory: sql/db_migrations

      - name: Create docker tags
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag git.prod.carsonnetworks.net/cdmeyer/weather-db-migrations:${{github.run_number}} git.prod.carsonnetworks.net/cdmeyer/weather-db-migrations:${{ needs.build.outputs.version }}
          docker tag git.prod.carsonnetworks.net/cdmeyer/weather-db-migrations:${{github.run_number}} git.prod.carsonnetworks.net/cdmeyer/weather-db-migrations:latest-release

      - name: Push build tag
        run: docker push git.prod.carsonnetworks.net/cdmeyer/weather-db-migrations:${{github.run_number}}

      - name: Push release tags
        if: github.ref == 'refs/heads/master'
        run: |
          docker push git.prod.carsonnetworks.net/cdmeyer/weather-db-migrations:${{ needs.build.outputs.version }}
          docker push git.prod.carsonnetworks.net/cdmeyer/weather-db-migrations:latest-release
